--- 
- 
  become: true
  become_method: sudo
  hosts: TestGroup
  name: "install apache and configure"
  tasks: 
    - 
      name: "install apache"
      yum: "pkg=httpd state=latest"
    - 
      name: "ensure apache is running"
      service: "name=httpd state=started enabled=yes"
    - 
      name: "html file setup"
      file:
        path: /var/www/html/index.html
        content: "Hello W0rld"
        state: touch
