--- 
- 
  become: true
  become_method: sudo
  #remote_user: root
  hosts: TestGroup
  name: "install apache and configure"
  tasks: 
    - 
      name: "install apache"
      yum: "pkg=httpd state=latest"
    - 
      name: "ensure apache is running"
      service: "name=httpd state=started enabled=yes"
    - 
      name: "html file setup"
      copy:
        dest: /var/www/html/index.html
        content: "This is where you host your website. Hello World!"


